/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    stats: Stat;
    services: Service;
    testimonials: Testimonial;
    partners: Partner;
    cities: City;
    'faq-items': FaqItem;
    'blog-posts': BlogPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'fr' | 'de' | 'nl' | 'it' | 'es')
    | ('en' | 'fr' | 'de' | 'nl' | 'it' | 'es')[];
  globals: {
    hero: Hero;
    'impact-section': ImpactSection;
    'services-section': ServicesSection;
    'partners-section': PartnersSection;
    'testimonials-section': TestimonialsSection;
    'cities-section': CitiesSection;
    'faq-section': FaqSection;
    'cta-section': CtaSection;
    'about-page': AboutPage;
    'outdoor-farm-page': OutdoorFarmPage;
    'indoor-farm-page': IndoorFarmPage;
    'careers-page': CareersPage;
    'contact-page': ContactPage;
    'educational-activities-page': EducationalActivitiesPage;
    'community-engagement-page': CommunityEngagementPage;
    'commercial-real-estate-page': CommercialRealEstatePage;
    'corporations-page': CorporationsPage;
    'schools-page': SchoolsPage;
    'partnerships-page': PartnershipsPage;
    'cities-page': CitiesPage;
    'blog-page': BlogPage;
    'privacy-policy-page': PrivacyPolicyPage;
    'terms-of-service-page': TermsOfServicePage;
    'cookie-policy-page': CookiePolicyPage;
    'roi-calculator-page': RoiCalculatorPage;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    'impact-section': ImpactSectionSelect<false> | ImpactSectionSelect<true>;
    'services-section': ServicesSectionSelect<false> | ServicesSectionSelect<true>;
    'partners-section': PartnersSectionSelect<false> | PartnersSectionSelect<true>;
    'testimonials-section': TestimonialsSectionSelect<false> | TestimonialsSectionSelect<true>;
    'cities-section': CitiesSectionSelect<false> | CitiesSectionSelect<true>;
    'faq-section': FaqSectionSelect<false> | FaqSectionSelect<true>;
    'cta-section': CtaSectionSelect<false> | CtaSectionSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'outdoor-farm-page': OutdoorFarmPageSelect<false> | OutdoorFarmPageSelect<true>;
    'indoor-farm-page': IndoorFarmPageSelect<false> | IndoorFarmPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'educational-activities-page': EducationalActivitiesPageSelect<false> | EducationalActivitiesPageSelect<true>;
    'community-engagement-page': CommunityEngagementPageSelect<false> | CommunityEngagementPageSelect<true>;
    'commercial-real-estate-page': CommercialRealEstatePageSelect<false> | CommercialRealEstatePageSelect<true>;
    'corporations-page': CorporationsPageSelect<false> | CorporationsPageSelect<true>;
    'schools-page': SchoolsPageSelect<false> | SchoolsPageSelect<true>;
    'partnerships-page': PartnershipsPageSelect<false> | PartnershipsPageSelect<true>;
    'cities-page': CitiesPageSelect<false> | CitiesPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'privacy-policy-page': PrivacyPolicyPageSelect<false> | PrivacyPolicyPageSelect<true>;
    'terms-of-service-page': TermsOfServicePageSelect<false> | TermsOfServicePageSelect<true>;
    'cookie-policy-page': CookiePolicyPageSelect<false> | CookiePolicyPageSelect<true>;
    'roi-calculator-page': RoiCalculatorPageSelect<false> | RoiCalculatorPageSelect<true>;
  };
  locale: 'en' | 'fr' | 'de' | 'nl' | 'it' | 'es';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Media library for images and files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Impact statistics displayed on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * The numeric value (e.g., 2500)
   */
  value: number;
  /**
   * Text after the number (e.g., "+", "M", "%")
   */
  suffix?: string | null;
  /**
   * Short label (e.g., "Beehives Installed")
   */
  label: string;
  /**
   * Longer description for tooltip or detail view
   */
  description?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Service offerings displayed on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Lucide icon name
   */
  icon: 'Leaf' | 'Building2' | 'GraduationCap' | 'Heart' | 'Users' | 'Sprout';
  title: string;
  description: string;
  /**
   * List of features/benefits for this service
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client testimonials displayed on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The testimonial text
   */
  quote: string;
  /**
   * Name of the person giving the testimonial
   */
  author: string;
  /**
   * Job title or role
   */
  role?: string | null;
  /**
   * Company or organization name
   */
  company: string;
  /**
   * Key phrase to highlight (optional)
   */
  highlight?: string | null;
  /**
   * Photo of the person
   */
  image?: (number | null) | Media;
  /**
   * Company logo
   */
  companyLogo?: (number | null) | Media;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Partner logos displayed on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Partner company name
   */
  name: string;
  /**
   * Partner logo (SVG or PNG recommended)
   */
  logo?: (number | null) | Media;
  /**
   * Partner website URL (optional)
   */
  website?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cities where MicroHabitat operates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  /**
   * City name
   */
  name: string;
  /**
   * Country name
   */
  country: string;
  /**
   * Geographic region for filtering
   */
  region: 'north-america' | 'europe';
  /**
   * URL-friendly identifier (e.g., "montreal", "new-york")
   */
  slug: string;
  /**
   * City image (recommended: 640x480px)
   */
  image?: (number | null) | Media;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  /**
   * FAQ category for grouping
   */
  category:
    | 'General Urban Farming Queries'
    | 'About Us'
    | 'Technical'
    | 'Products and Services'
    | 'Engagement'
    | 'Collaboration'
    | 'Getting Started'
    | 'Safety';
  /**
   * Display order within category (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles and news
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short summary for listing pages (max 200 chars)
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Author name
   */
  author: string;
  publishedDate: string;
  categories?:
    | ('CSR' | 'ESG' | 'Green Buildings' | 'Urban Farming' | 'Sustainability' | 'News' | 'Case Studies' | 'Education')[]
    | null;
  /**
   * Featured image for the article
   */
  featuredImage?: (number | null) | Media;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  value?: T;
  suffix?: T;
  label?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  highlight?: T;
  image?: T;
  companyLogo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  region?: T;
  slug?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  publishedDate?: T;
  categories?: T;
  featuredImage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Hero section content for the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Main headline (first part)
   */
  title: string;
  /**
   * Highlighted part of the headline (displayed in accent color)
   */
  titleHighlight: string;
  /**
   * Supporting text below the headline
   */
  subtitle: string;
  /**
   * Primary call-to-action button text
   */
  ctaPrimary: string;
  /**
   * Secondary call-to-action button text
   */
  ctaSecondary?: string | null;
  /**
   * Hero background or featured image
   */
  image?: (number | null) | Media;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Impact/statistics section content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-section".
 */
export interface ImpactSection {
  id: number;
  /**
   * Section label (e.g., "Our Impact")
   */
  label: string;
  /**
   * Section heading (first part)
   */
  heading: string;
  /**
   * Highlighted part of heading
   */
  headingHighlight: string;
  description: string;
  /**
   * Gallery images for the impact section
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Services section header content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section".
 */
export interface ServicesSection {
  id: number;
  /**
   * Section label (e.g., "Our Services")
   */
  label: string;
  heading: string;
  headingHighlight: string;
  description: string;
  /**
   * Call-to-action text
   */
  ctaText?: string | null;
  /**
   * Button text
   */
  ctaButtonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Partners section header content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-section".
 */
export interface PartnersSection {
  id: number;
  /**
   * Section label (e.g., "Our Partners")
   */
  label: string;
  heading: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Testimonials section header content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-section".
 */
export interface TestimonialsSection {
  id: number;
  /**
   * Section label (e.g., "Testimonials")
   */
  label: string;
  heading: string;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Cities section header content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities-section".
 */
export interface CitiesSection {
  id: number;
  /**
   * Section label (e.g., "Our Locations")
   */
  label: string;
  heading: string;
  description?: string | null;
  ctaText?: string | null;
  ctaButtonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * FAQ section header content and FAQ page SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section".
 */
export interface FaqSection {
  id: number;
  /**
   * Section label (e.g., "FAQ")
   */
  label: string;
  heading: string;
  description?: string | null;
  ctaText?: string | null;
  ctaButtonText?: string | null;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Call-to-action section content (bottom of homepage)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-section".
 */
export interface CtaSection {
  id: number;
  label: string;
  heading: string;
  headingHighlight: string;
  description: string;
  /**
   * Primary button text
   */
  ctaPrimary: string;
  /**
   * Secondary button/link text
   */
  ctaSecondary?: string | null;
  /**
   * Email for secondary CTA
   */
  ctaSecondaryEmail?: string | null;
  /**
   * Trust badges/indicators (e.g., "100+ Happy Clients")
   */
  trustIndicators?:
    | {
        indicator: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * About page content and SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroLabel: string;
  heroTitle: string;
  heroTitleHighlight: string;
  missionLabel: string;
  missionTitle: string;
  missionParagraph1: string;
  missionParagraph2?: string | null;
  solidarityLabel?: string | null;
  solidarityTitle?: string | null;
  solidarityDescription?: string | null;
  impactStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  storyLabel?: string | null;
  storyTitle?: string | null;
  storyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Outdoor farm page content and SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outdoor-farm-page".
 */
export interface OutdoorFarmPage {
  id: number;
  heroLabel: string;
  heroTitle: string;
  heroTitleHighlight: string;
  heroDescription: string;
  servicesLabel?: string | null;
  servicesTitle?: string | null;
  services?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  galleryLabel?: string | null;
  galleryTitle?: string | null;
  packagesLabel?: string | null;
  packagesTitle?: string | null;
  packages?:
    | {
        name: string;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  requirementsLabel?: string | null;
  requirementsTitle?: string | null;
  requirementsDescription?: string | null;
  requirements?:
    | {
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  requirementsCardTitle?: string | null;
  requirementsCardDescription?: string | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaViewFaq?: string | null;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Indoor farm page content and SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indoor-farm-page".
 */
export interface IndoorFarmPage {
  id: number;
  heroLabel: string;
  heroTitle: string;
  heroTitleHighlight: string;
  heroDescription: string;
  featuresLabel?: string | null;
  featuresTitle?: string | null;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  benefitsLabel?: string | null;
  benefitsTitle?: string | null;
  benefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Careers page content and SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  heroLabel: string;
  heroTitle: string;
  heroTitleHighlight: string;
  introText?: string | null;
  valuesLabel?: string | null;
  valuesTitle?: string | null;
  values?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  whyJoinLabel?: string | null;
  whyJoinTitle?: string | null;
  benefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact page content and SEO
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heroLabel: string;
  heroTitle: string;
  heroTitleHighlight: string;
  introText?: string | null;
  offices?:
    | {
        name: string;
        /**
         * e.g., "Headquarters", "Regional Office"
         */
        type?: string | null;
        address: string;
        city: string;
        country: string;
        id?: string | null;
      }[]
    | null;
  formTitle?: string | null;
  formSubtitle?: string | null;
  quickLinks?:
    | {
        label: string;
        /**
         * URL, email, or phone number
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Educational Activities page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-activities-page".
 */
export interface EducationalActivitiesPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Community Engagement page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-engagement-page".
 */
export interface CommunityEngagementPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Commercial Real Estate page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commercial-real-estate-page".
 */
export interface CommercialRealEstatePage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Corporations page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporations-page".
 */
export interface CorporationsPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Schools page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools-page".
 */
export interface SchoolsPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Partnerships page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships-page".
 */
export interface PartnershipsPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Cities listing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities-page".
 */
export interface CitiesPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Blog listing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Privacy Policy page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page".
 */
export interface PrivacyPolicyPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Terms of Service page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-service-page".
 */
export interface TermsOfServicePage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the Cookie Policy page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy-page".
 */
export interface CookiePolicyPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO settings for the ROI Calculator page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roi-calculator-page".
 */
export interface RoiCalculatorPage {
  id: number;
  seo?: {
    /**
     * Max 60 characters for optimal display in search results
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters for optimal display in search results
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL (leave blank to use default)
     */
    canonical?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  titleHighlight?: T;
  subtitle?: T;
  ctaPrimary?: T;
  ctaSecondary?: T;
  image?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-section_select".
 */
export interface ImpactSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  headingHighlight?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section_select".
 */
export interface ServicesSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  headingHighlight?: T;
  description?: T;
  ctaText?: T;
  ctaButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-section_select".
 */
export interface PartnersSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-section_select".
 */
export interface TestimonialsSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities-section_select".
 */
export interface CitiesSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  description?: T;
  ctaText?: T;
  ctaButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section_select".
 */
export interface FaqSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  description?: T;
  ctaText?: T;
  ctaButtonText?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-section_select".
 */
export interface CtaSectionSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  headingHighlight?: T;
  description?: T;
  ctaPrimary?: T;
  ctaSecondary?: T;
  ctaSecondaryEmail?: T;
  trustIndicators?:
    | T
    | {
        indicator?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroLabel?: T;
  heroTitle?: T;
  heroTitleHighlight?: T;
  missionLabel?: T;
  missionTitle?: T;
  missionParagraph1?: T;
  missionParagraph2?: T;
  solidarityLabel?: T;
  solidarityTitle?: T;
  solidarityDescription?: T;
  impactStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  storyLabel?: T;
  storyTitle?: T;
  storyContent?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outdoor-farm-page_select".
 */
export interface OutdoorFarmPageSelect<T extends boolean = true> {
  heroLabel?: T;
  heroTitle?: T;
  heroTitleHighlight?: T;
  heroDescription?: T;
  servicesLabel?: T;
  servicesTitle?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  galleryLabel?: T;
  galleryTitle?: T;
  packagesLabel?: T;
  packagesTitle?: T;
  packages?:
    | T
    | {
        name?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  requirementsLabel?: T;
  requirementsTitle?: T;
  requirementsDescription?: T;
  requirements?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  requirementsCardTitle?: T;
  requirementsCardDescription?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  ctaViewFaq?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indoor-farm-page_select".
 */
export interface IndoorFarmPageSelect<T extends boolean = true> {
  heroLabel?: T;
  heroTitle?: T;
  heroTitleHighlight?: T;
  heroDescription?: T;
  featuresLabel?: T;
  featuresTitle?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  benefitsLabel?: T;
  benefitsTitle?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  heroLabel?: T;
  heroTitle?: T;
  heroTitleHighlight?: T;
  introText?: T;
  valuesLabel?: T;
  valuesTitle?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whyJoinLabel?: T;
  whyJoinTitle?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroLabel?: T;
  heroTitle?: T;
  heroTitleHighlight?: T;
  introText?: T;
  offices?:
    | T
    | {
        name?: T;
        type?: T;
        address?: T;
        city?: T;
        country?: T;
        id?: T;
      };
  formTitle?: T;
  formSubtitle?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-activities-page_select".
 */
export interface EducationalActivitiesPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-engagement-page_select".
 */
export interface CommunityEngagementPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commercial-real-estate-page_select".
 */
export interface CommercialRealEstatePageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporations-page_select".
 */
export interface CorporationsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools-page_select".
 */
export interface SchoolsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships-page_select".
 */
export interface PartnershipsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities-page_select".
 */
export interface CitiesPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page_select".
 */
export interface PrivacyPolicyPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-service-page_select".
 */
export interface TermsOfServicePageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy-page_select".
 */
export interface CookiePolicyPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roi-calculator-page_select".
 */
export interface RoiCalculatorPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}